version: "3"

services:
    mq:
        build:
            context: .
            dockerfile: Dockerfile.mq
        ports:
            - 15672:15672
            - 5672:5672
        environment:
            RABBITMQ_DEFAULT_USER: "guest"
            RABBITMQ_DEFAULT_PASS: "guest"
            RABBITMQ_DEFAULT_VHOST: "/"
        networks:
            - ingress

    proxy:
        image: shopify/toxiproxy
        ports:
            - 8474:8474
            - 35672:35672
        networks:
            - ingress

networks: 
    ingress:
        driver: bridge